export default () => ({
  struktur: [],
  btn: true,
  value: [],
  options: [
    { name: "data santri", code: 0 },
    { name: "kelas", code: 1 },
    { name: "asrama", code: 2 },
    { name: "halaqah", code: 3 },
    { name: "ekskull", code: 4 },
    { name: "pengampu", code: 5 },
    { name: "wali kelas", code: 6 },
    { name: "musyrif", code: 7 },
    { name: "pengajar", code: 8 },
    { name: "setup halaqah", code: 9 },
    { name: "setup asrama", code: 10 },
    { name: "setup kelas", code: 11 },
    { name: "setup mapel", code: 12 },
    { name: "setup pelanggaran", code: 13 },
    { name: "setup absensi", code: 14 },
    { name: "report mapel", code: 15 },
    { name: "report tahfidz", code: 16 },
    { name: "report absensi", code: 17 },
    { name: "report pelanggaran", code: 18 },
    { name: "report jurnal", code: 19 },
    { name: "report pengampu", code: 20 },
    { name: "page asrama", code: 21 },
    { name: "page pelanggaran", code: 22 },
    { name: "page ekskull", code: 23 },
    { name: "laundry", code: 24 },
    { name: "absensi pengampu", code: 25 },
    { name: "none", code: 26 },
  ],

  // partikel
  updateData: "",
})
