export default () => ({
  mapel: [],
  kelas: [],
  jurusan: [],
  selectKelas: "",
  selectSemester: "",
  updateData: "",
  updateDataPenilaian: "",
  Penilaian: [],
  btn: true,
  value: [],
  status: false,
  label: "close",
  options: [
    { name: "senin-1", code: 0 },
    { name: "senin-2", code: 1 },
    { name: "senin-3", code: 2 },
    { name: "selasa-1", code: 3 },
    { name: "selasa-2", code: 4 },
    { name: "selasa-3", code: 5 },
    { name: "rabu-1", code: 6 },
    { name: "rabu-2", code: 7 },
    { name: "rabu-3", code: 8 },
    { name: "kamis-1", code: 9 },
    { name: "kamis-2", code: 10 },
    { name: "kamis-3", code: 11 },
    { name: "jumat-1", code: 12 },
    { name: "jumat-2", code: 13 },
    { name: "jumat-3", code: 14 },
    { name: "sabtu-1a", code: 15 },
    { name: "sabtu-2a", code: 16 },
    { name: "sabtu-3a", code: 17 },
    { name: "sabtu-4a", code: 18 },
    { name: "sabtu-5a", code: 19 },
    { name: "sabtu-6a", code: 20 },
    { name: "sabtu-7a", code: 21 },
    { name: "sabtu-1b", code: 22 },
    { name: "sabtu-2b", code: 23 },
    { name: "sabtu-3b", code: 24 },
    { name: "sabtu-4b", code: 25 },
    { name: "sabtu-5b", code: 26 },
    { name: "sabtu-6b", code: 27 },
    { name: "sabtu-7b", code: 28 },
    { name: "sabtu-1c", code: 29 },
    { name: "sabtu-2c", code: 30 },
    { name: "sabtu-3c", code: 31 },
    { name: "sabtu-4c", code: 32 },
    { name: "sabtu-5c", code: 33 },
    { name: "sabtu-6c", code: 34 },
    { name: "sabtu-7c", code: 35 },
  ],
});
