export default () => ({
  mapel: [],
  kelas: [],
  jurusan: [],
  selectKelas: '',
  updateData: '',
  btn: true,
  value: [],
  options: [
    { name: "senin-1", code: 0 },
    { name: "senin-2", code: 1 },
    { name: "senin-3", code: 2 },
    { name: "selasa-1", code: 3 },
    { name: "selasa-2", code: 4 },
    { name: "selasa-3", code: 5 },
    { name: "rabu-1", code: 6 },
    { name: "rabu-2", code: 7 },
    { name: "rabu-3", code: 8 },
    { name: "kamis-1", code: 9 },
    { name: "kamis-2", code: 10 },
    { name: "kamis-3", code: 11 },
    { name: "jumat-1", code: 12 },
    { name: "jumat-2", code: 13 },
    { name: "jumat-3", code: 14 },
    { name: "sabtu-1", code: 15 },
    { name: "sabtu-2", code: 16 },
    { name: "sabtu-3", code: 17 },
  ],
})
