export default () => ({
  activeMenu: null, // Menyimpan menu yang sedang aktif (untuk menampilkan sub-menu)
  listAsrama: false,
  listTahfidz: false,
  listSettings: false,
  listKelas: false,
  listMatan: false,
  listReport: false,
  listLaundry: false,
  listEkskull: false,
  listLaporan: false,
  listKebersihan: false,
  absensiSubList: false,
  santriSubList: false,
  pegawaiSubList: false,
  databaseSubList: false,
  tahfidzSubList: false,
  tahfidz2SubList: false,
  kelasSubList: false,
  matanSubList: false,
  matan2SubList: false,
  settingLaundrySubList: false,

  isSidebar: true,
  isSidebarOpen: true,
});
